[package]
name = "kvs"
version = "0.1.0"
edition = "2021"
description = "key-value store"

[dependencies]
clap = { version = "4.2.2", features = ["derive"] }

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"

